# team_factors.py

TEAM_FACTORS = {
    "Boston Celtics": {
        "season_offense": 118,
        "season_defense": 110,
        "home_offense": 120,
        "home_defense": 108,
        "away_offense": 116,
        "away_defense": 112,
        "recent_5_offense": 119,
        "recent_5_defense": 109,
        "recent_5_margin": 10,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Oklahoma City Thunder": {
        "season_offense": 120,
        "season_defense": 112,
        "home_offense": 122,
        "home_defense": 110,
        "away_offense": 118,
        "away_defense": 114,
        "recent_5_offense": 121,
        "recent_5_defense": 111,
        "recent_5_margin": 9,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Detroit Pistons": {
        "season_offense": 110,
        "season_defense": 118,
        "home_offense": 111,
        "home_defense": 117,
        "away_offense": 109,
        "away_defense": 119,
        "recent_5_offense": 109,
        "recent_5_defense": 119,
        "recent_5_margin": -8,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Philadelphia 76ers": {
        "season_offense": 112,
        "season_defense": 111,
        "home_offense": 113,
        "home_defense": 109,
        "away_offense": 111,
        "away_defense": 113,
        "recent_5_offense": 111,
        "recent_5_defense": 112,
        "recent_5_margin": -1,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Phoenix Suns": {
        "season_offense": 115,
        "season_defense": 113,
        "home_offense": 116,
        "home_defense": 112,
        "away_offense": 114,
        "away_defense": 114,
        "recent_5_offense": 116,
        "recent_5_defense": 114,
        "recent_5_margin": 2,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Orlando Magic": {
        "season_offense": 108,
        "season_defense": 109,
        "home_offense": 109,
        "home_defense": 107,
        "away_offense": 107,
        "away_defense": 111,
        "recent_5_offense": 109,
        "recent_5_defense": 108,
        "recent_5_margin": 1,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Portland Trail Blazers": {
        "season_offense": 107,
        "season_defense": 119,
        "home_offense": 108,
        "home_defense": 118,
        "away_offense": 106,
        "away_defense": 120,
        "recent_5_offense": 106,
        "recent_5_defense": 120,
        "recent_5_margin": -10,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Toronto Raptors": {
        "season_offense": 109,
        "season_defense": 115,
        "home_offense": 110,
        "home_defense": 114,
        "away_offense": 108,
        "away_defense": 116,
        "recent_5_offense": 108,
        "recent_5_defense": 116,
        "recent_5_margin": -7,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Atlanta Hawks": {
        "season_offense": 113,
        "season_defense": 120,
        "home_offense": 114,
        "home_defense": 119,
        "away_offense": 112,
        "away_defense": 121,
        "recent_5_offense": 114,
        "recent_5_defense": 119,
        "recent_5_margin": -4,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Minnesota Timberwolves": {
        "season_offense": 114,
        "season_defense": 108,
        "home_offense": 115,
        "home_defense": 106,
        "away_offense": 113,
        "away_defense": 110,
        "recent_5_offense": 113,
        "recent_5_defense": 108,
        "recent_5_margin": 5,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Houston Rockets": {
        "season_offense": 105,
        "season_defense": 112,
        "home_offense": 106,
        "home_defense": 111,
        "away_offense": 104,
        "away_defense": 113,
        "recent_5_offense": 106,
        "recent_5_defense": 111,
        "recent_5_margin": -3,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Los Angeles Lakers": {
        "season_offense": 116,
        "season_defense": 114,
        "home_offense": 117,
        "home_defense": 113,
        "away_offense": 115,
        "away_defense": 115,
        "recent_5_offense": 117,
        "recent_5_defense": 114,
        "recent_5_margin": 3,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Golden State Warriors": {
        "season_offense": 117,
        "season_defense": 116,
        "home_offense": 118,
        "home_defense": 114,
        "away_offense": 116,
        "away_defense": 118,
        "recent_5_offense": 118,
        "recent_5_defense": 115,
        "recent_5_margin": 2,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Milwaukee Bucks": {
        "season_offense": 119,
        "season_defense": 115,
        "home_offense": 120,
        "home_defense": 113,
        "away_offense": 118,
        "away_defense": 117,
        "recent_5_offense": 120,
        "recent_5_defense": 115,
        "recent_5_margin": 6,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Denver Nuggets": {
        "season_offense": 118,
        "season_defense": 111,
        "home_offense": 119,
        "home_defense": 109,
        "away_offense": 117,
        "away_defense": 113,
        "recent_5_offense": 118,
        "recent_5_defense": 112,
        "recent_5_margin": 5,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Miami Heat": {
        "season_offense": 109,
        "season_defense": 110,
        "home_offense": 110,
        "home_defense": 108,
        "away_offense": 108,
        "away_defense": 112,
        "recent_5_offense": 108,
        "recent_5_defense": 109,
        "recent_5_margin": 0,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Cleveland Cavaliers": {
        "season_offense": 112,
        "season_defense": 108,
        "home_offense": 113,
        "home_defense": 106,
        "away_offense": 111,
        "away_defense": 110,
        "recent_5_offense": 113,
        "recent_5_defense": 107,
        "recent_5_margin": 6,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "New York Knicks": {
        "season_offense": 111,
        "season_defense": 109,
        "home_offense": 112,
        "home_defense": 107,
        "away_offense": 110,
        "away_defense": 111,
        "recent_5_offense": 114,
        "recent_5_defense": 108,
        "recent_5_margin": 4,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "Indiana Pacers": {
        "season_offense": 121,
        "season_defense": 123,
        "home_offense": 122,
        "home_defense": 121,
        "away_offense": 120,
        "away_defense": 125,
        "recent_5_offense": 122,
        "recent_5_defense": 122,
        "recent_5_margin": 0,
        "recent_5_over_rate": 0.80,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Sacramento Kings": {
        "season_offense": 117,
        "season_defense": 118,
        "home_offense": 118,
        "home_defense": 116,
        "away_offense": 116,
        "away_defense": 120,
        "recent_5_offense": 118,
        "recent_5_defense": 118,
        "recent_5_margin": 1,
        "recent_5_over_rate": 0.60,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Dallas Mavericks": {
        "season_offense": 116,
        "season_defense": 114,
        "home_offense": 117,
        "home_defense": 112,
        "away_offense": 115,
        "away_defense": 116,
        "recent_5_offense": 116,
        "recent_5_defense": 113,
        "recent_5_margin": 3,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "LA Clippers": {
        "season_offense": 115,
        "season_defense": 112,
        "home_offense": 116,
        "home_defense": 110,
        "away_offense": 114,
        "away_defense": 114,
        "recent_5_offense": 115,
        "recent_5_defense": 111,
        "recent_5_margin": 4,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.60,
        "rest_days": 1,
        "back_to_back": False
    },
    "New Orleans Pelicans": {
        "season_offense": 114,
        "season_defense": 113,
        "home_offense": 115,
        "home_defense": 111,
        "away_offense": 113,
        "away_defense": 115,
        "recent_5_offense": 113,
        "recent_5_defense": 114,
        "recent_5_margin": -1,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Memphis Grizzlies": {
        "season_offense": 106,
        "season_defense": 115,
        "home_offense": 107,
        "home_defense": 113,
        "away_offense": 105,
        "away_defense": 117,
        "recent_5_offense": 105,
        "recent_5_defense": 116,
        "recent_5_margin": -8,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "San Antonio Spurs": {
        "season_offense": 112,
        "season_defense": 118,
        "home_offense": 113,
        "home_defense": 117,
        "away_offense": 111,
        "away_defense": 119,
        "recent_5_offense": 112,
        "recent_5_defense": 118,
        "recent_5_margin": -5,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Utah Jazz": {
        "season_offense": 113,
        "season_defense": 120,
        "home_offense": 114,
        "home_defense": 118,
        "away_offense": 112,
        "away_defense": 122,
        "recent_5_offense": 112,
        "recent_5_defense": 121,
        "recent_5_margin": -7,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Brooklyn Nets": {
        "season_offense": 108,
        "season_defense": 117,
        "home_offense": 109,
        "home_defense": 115,
        "away_offense": 107,
        "away_defense": 119,
        "recent_5_offense": 107,
        "recent_5_defense": 118,
        "recent_5_margin": -6,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Charlotte Hornets": {
        "season_offense": 106,
        "season_defense": 119,
        "home_offense": 107,
        "home_defense": 117,
        "away_offense": 105,
        "away_defense": 121,
        "recent_5_offense": 106,
        "recent_5_defense": 120,
        "recent_5_margin": -8,
        "recent_5_over_rate": 0.40,
        "recent_5_ats_rate": 0.40,
        "rest_days": 1,
        "back_to_back": False
    },
    "Chicago Bulls": {
        "season_offense": 111,
        "season_defense": 112,
        "home_offense": 112,
        "home_defense": 110,
        "away_offense": 110,
        "away_defense": 114,
        "recent_5_offense": 111,
        "recent_5_defense": 112,
        "recent_5_margin": -1,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.50,
        "rest_days": 1,
        "back_to_back": False
    },
    "Washington Wizards": {
        "season_offense": 107,
        "season_defense": 122,
        "home_offense": 108,
        "home_defense": 120,
        "away_offense": 106,
        "away_defense": 124,
        "recent_5_offense": 106,
        "recent_5_defense": 123,
        "recent_5_margin": -11,
        "recent_5_over_rate": 0.50,
        "recent_5_ats_rate": 0.30,
        "rest_days": 1,
        "back_to_back": False
    }
}


DEFAULT_FACTORS = {
    "season_offense": 110,
    "season_defense": 110,
    "home_offense": 111,
    "home_defense": 109,
    "away_offense": 109,
    "away_defense": 111,
    "recent_5_offense": 110,
    "recent_5_defense": 110,
    "recent_5_margin": 0,
    "recent_5_over_rate": 0.50,
    "recent_5_ats_rate": 0.50,
    "rest_days": 1,
    "back_to_back": False
}


def get_team_factors(team_name: str) -> dict:
    return TEAM_FACTORS.get(team_name, DEFAULT_FACTORS.copy())


# =========================
# 多因子讓分模型資料
# 數字越高，代表球隊整體越強
# =========================

team_power = {
    "Oklahoma City Thunder": 92,
    "Boston Celtics": 91,
    "Cleveland Cavaliers": 88,
    "Denver Nuggets": 87,
    "Minnesota Timberwolves": 86,
    "New York Knicks": 84,
    "Los Angeles Lakers": 82,
    "Houston Rockets": 81,
    "Orlando Magic": 80,
    "Detroit Pistons": 78,
    "Atlanta Hawks": 77,
    "Phoenix Suns": 76,
    "Golden State Warriors": 76,
    "Milwaukee Bucks": 75,
    "Indiana Pacers": 75,
    "Miami Heat": 74,
    "Philadelphia 76ers": 72,
    "Dallas Mavericks": 72,
    "Sacramento Kings": 71,
    "Chicago Bulls": 70,
    "Toronto Raptors": 68,
    "San Antonio Spurs": 68,
    "Portland Trail Blazers": 66,
    "Brooklyn Nets": 65,
    "Charlotte Hornets": 63,
    "Utah Jazz": 62,
    "Washington Wizards": 60,
}